"""Create RBAC models

Revision ID: d4a2ca31ff4a
Revises:
 Create Date: 2026-01-16 18:23:15.380117
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd4a2ca31ff4a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_elements',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('key', sa.String(length=50), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_business_elements_id'), 'business_elements', ['id'], unique=False)
    op.create_index(op.f('ix_business_elements_key'), 'business_elements', ['key'], unique=True)
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('access_roles_rules',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('element_id', sa.Integer(), nullable=False),
                    sa.Column('create_permission', sa.Boolean(), nullable=False),
                    sa.Column('read_permission', sa.Boolean(), nullable=False),
                    sa.Column('read_all_permission', sa.Boolean(), nullable=False),
                    sa.Column('update_permission', sa.Boolean(), nullable=False),
                    sa.Column('update_all_permission', sa.Boolean(), nullable=False),
                    sa.Column('delete_permission', sa.Boolean(), nullable=False),
                    sa.Column('delete_all_permission', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['element_id'], ['business_elements.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('role_id', 'element_id', name='uq_role_element')
                    )
    op.create_index(op.f('ix_access_roles_rules_id'), 'access_roles_rules', ['id'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('first_name', sa.String(length=100), nullable=True),
                    sa.Column('last_name', sa.String(length=100), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_access_roles_rules_id'), table_name='access_roles_rules')
    op.drop_table('access_roles_rules')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_business_elements_key'), table_name='business_elements')
    op.drop_index(op.f('ix_business_elements_id'), table_name='business_elements')
    op.drop_table('business_elements')
    # ### end Alembic commands ###
